In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [78]:
dataset=pd.read_csv("C:/Users/bhatk/OneDrive/Documents/jupyter/diabetes_data_prediction/diabetes_prediction_dataset.csv")

In [79]:
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [80]:
dataset.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [81]:
dataset.gender.unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [82]:
from sklearn.preprocessing import LabelEncoder

In [83]:
le_gender=LabelEncoder()
le_smoking=LabelEncoder()


In [84]:
dataset.gender=le_gender.fit_transform(dataset.gender)

In [85]:
dataset.smoking_history=le_smoking.fit_transform(dataset.smoking_history)

In [86]:
dataset

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99995       0  80.0             0              0                0  27.32   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [87]:
for num, category in enumerate(le_gender.classes_):
    print(f"Numerical value {num} maps to categorical value '{category}'")

Numerical value 0 maps to categorical value 'Female'
Numerical value 1 maps to categorical value 'Male'
Numerical value 2 maps to categorical value 'Other'


In [88]:
for num, category in enumerate(le_smoking.classes_):
    print(f"Numerical value {num} maps to categorical value '{category}'")

Numerical value 0 maps to categorical value 'No Info'
Numerical value 1 maps to categorical value 'current'
Numerical value 2 maps to categorical value 'ever'
Numerical value 3 maps to categorical value 'former'
Numerical value 4 maps to categorical value 'never'
Numerical value 5 maps to categorical value 'not current'


In [89]:
x=dataset.iloc[:,:-1].values

In [90]:
x

array([[  0.  ,  80.  ,   0.  , ...,  25.19,   6.6 , 140.  ],
       [  0.  ,  54.  ,   0.  , ...,  27.32,   6.6 ,  80.  ],
       [  1.  ,  28.  ,   0.  , ...,  27.32,   5.7 , 158.  ],
       ...,
       [  1.  ,  66.  ,   0.  , ...,  27.83,   5.7 , 155.  ],
       [  0.  ,  24.  ,   0.  , ...,  35.42,   4.  , 100.  ],
       [  0.  ,  57.  ,   0.  , ...,  22.43,   6.6 ,  90.  ]])

In [91]:
y=dataset.iloc[:,-1].values

In [92]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [93]:
from sklearn.model_selection import train_test_split

In [94]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [95]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)


In [96]:
from sklearn.linear_model import LogisticRegression

In [97]:
log=LogisticRegression()

In [98]:
log.fit(X_train_scaled,y_train)

LogisticRegression()

In [99]:
y_predict=log.predict(X_test_scaled)

In [100]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [101]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [102]:
from sklearn.metrics import accuracy_score

In [103]:
acc=accuracy_score(y_test,y_predict)

In [104]:
acc

0.9595666666666667

In [105]:
from xgboost import XGBClassifier

xgb = XGBClassifier(random_state=0)
xgb.fit(X_train_scaled, y_train)
y_pred = xgb.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy with XGBoost:", accuracy)


Accuracy with XGBoost: 0.9707333333333333


In [106]:
import pickle

In [107]:
pickle.dump(xgb,open('xgbmodel.pkl','wb'))

In [108]:
pickled_model=pickle.load(open('xgbmodel.pkl','rb'))

In [111]:
data=np.array([[0, 80.0, 0, 1, 4, 25.19, 6.6, 140]])

In [112]:
new_data = scaler.transform(data)

In [113]:
prediction=pickled_model.predict(new_data)

In [123]:
prediction

array([0])

In [124]:
probabilities = pickled_model.predict_proba(new_data)

In [125]:
probabilities

array([[0.90080047, 0.09919953]], dtype=float32)

In [131]:
confidence = max(probabilities[0])


In [132]:
print(confidence)

0.90080047
